---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: my-app

spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  #the template is for the pod creation, which is basically having the container
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginxv2-container
          image: majjivinaykumar/nginx:v2
          ports:
            - containerPort: 80
